GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/235

###
POST http://localhost:3000/subscribers
Content-Types: application/json

{
    "name": "John Doe",
    "subscribedToChannel": "Fishing"
}

### 
DELETE http://localhost:3000/subscribers

PATCH http://localhost:3000/subscribers
Content-Types: application/json

{
    "name": "John Doe",
    "subscribedToChannel": "Running"
}